import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

const id = (name: string) => text(name).primaryKey();
export const car = sqliteTable("car", { id: id("id"), name: text("name").notNull(), manufacturer: text("manufacturer"), model: text("model"), scale: text("scale"), notes: text("notes"), createdAt: text("created_at").notNull(), archivedAt: text("archived_at") });
export const component = sqliteTable("component", { id: id("id"), carId: text("car_id").notNull(), slot: text("slot").notNull(), name: text("name").notNull(), serialNumber: text("serial_number"), notes: text("notes"), installedAt: text("installed_at").notNull(), removedAt: text("removed_at") });
export const driveSession = sqliteTable("drive_session", { id: id("id"), carId: text("car_id").notNull(), startedAt: text("started_at").notNull(), durationMinutes: integer("duration_minutes"), conditions: text("conditions"), notes: text("notes") });
export const maintenancePlan = sqliteTable("maintenance_plan", { id: id("id"), carId: text("car_id").notNull(), componentId: text("component_id").notNull(), name: text("name").notNull(), intervalDays: integer("interval_days"), intervalSessions: integer("interval_sessions"), baselineAt: text("baseline_at").notNull(), status: text("status").notNull(), pausedAt: text("paused_at") });
export const serviceRecord = sqliteTable("service_record", { id: id("id"), carId: text("car_id").notNull(), componentId: text("component_id"), performedAt: text("performed_at").notNull(), description: text("description").notNull(), baselineAt: text("baseline_at").notNull() });
export const photo = sqliteTable("photo", { id: id("id"), carId: text("car_id").notNull(), objectKey: text("object_key").notNull().unique(), contentType: text("content_type").notNull(), createdAt: text("created_at").notNull() });
